### ISSUE TITLE
Just Testing

### ISSUE THREAD

**Issue by mbabker** [jtester/tests#105]
Hello!

**Comment by mbabker** [comment]
Here's a comment I'm going to delete.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/jtests/105">issues.joomla.org/jtests/105</a>.</sub>

**Comment by elkuku** [comment]
Set to "closed" on behalf of @elkuku by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://trackertest-elkuku.rhcloud.com/tracker/jtests/105">trackertest-elkuku.rhcloud.com/jtests/105</a>

**Comment by elkuku** [comment]
Set to "closed" on behalf of @elkuku by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://jtracker.local/tracker/jtests/105">jtracker.local/jtests/105</a>
